###########
# site.title

title: "procslash"
description: An outlet for things that need expression
url: "procslash.github.io"


#########################
# more settings

markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

sass:
  sass_dir: css
  style:    compressed

baseurl: ""
permalink: pretty
timezone: Asia/Kolkata
future: false

exclude:
- README.md
- LICENSE.md
